### ISSUE TITLE
nmodes2numdiff.py implicitly adds the displacements in atomic units to coordinates in angstroms

### ISSUE THREAD

**Issue by marcin-witkowski** [jensengrouppsu/scripts#2]
At present, nmodes2numdiff.py has a following code for generating coordinates for numerical differentiation (lines 204-208):

`                nmode = new.normal_modes[i]`
`                if mp == 'm':`
`                    new.coordinates = new.coordinates - nmode * sR`
`                else:`
`                    new.coordinates = new.coordinates + nmode * sR`

where sR is the differentiation step size (decided by user) and nmode is the atom displacement matrix. The problem is: new.coordinates is in angstrom, while nmode is in atomic units. Although the net effect is just changing the sR by a factor of ANGSTROM2BOHR, the user may be unaware of that.

A basic solution could be just to implement the reasonable conversion in-place, but I'm not sure what is the intended unit of atom displacement matrix returned by chemPackage - thus I am not making a pull request as of yet.

**Comment by markbronsonjr** [comment]
where did you get that nmode was in atomic units? 
normal_modes[i] comes from line 66 of https://github.com/jensengrouppsu/chemPackage/blob/master/chemPackage/ams/vibrations.py (for ams, it's similar for adf and nwchem) 
There the normal_modes normalized and then has the conversion from bohr to angstroms attached to it, this makes it so the sR can be given in au and then used directly even though the coordinates are in angstrom.  
```
    # Simultaneously normalize in Bohr then convert to Angstroms
    for i in range(self.nmodes):
        self.normal_modes[i] *= B2A / norm(self.normal_modes[i].flatten())
```

**Comment by marcin-witkowski** [comment]
Thanks for looking into that!

I got it from comparing the outputs of AMS and the displacements calculated by nmodes2numdiff. I expected the displacements to be (sR in angstroms)*(whatever displacement is printed by AMS after normalization) but they are smaller by a factor of about two. I assumed that's because they are in atomic units, but that's actually backwards.

Basically, I expected sR to be in angstroms (that would be intuitive to me, as the coordinates are in angstroms), as a scaling factor for a normalized ("unitless") mode displacement. I guess I do not really understand the necessity of the B2A factor in the code snippet you have provided. Is there a reason for ensuring that the displacements are normalized to 1 Bohr, rather than 1 angstrom?

Thanks again for everything!

**Comment by markbronsonjr** [comment]
Ok, gotcha.

As for the factor of B2A, rather than thinking of it as normalizing the displacements to 1 bohr, it's better to think of normal_modes as holding the conversion factor such that sR can be given in bohr. 

The way that the chemPackage handles normal_modes isn't obvious and should probably be changed, so I'll look into that. For now, I just added comments to nmodes2numdiff.py to make things a bit more clear.

**Comment by marcin-witkowski** [comment]
Sure, that helps a lot for now, thank you for that!
